baseurl: /
languageCode: en-us
title: The Real Donald Trump 2020 - Prison Edition
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: 'https-therealdonaldtrump2020-com'
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
permalinks:
  post: '/:year/:month/:day/:slug/'
menu:
  main:
    - name: About
      url: /about/
params:
  description: A Trump 2020 Campaign Paradoy Account
  highlightjsVersion: 9.12.0
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  favicon: favicon.ico
  logo:
    url: logo.png
    width: 50
    height: 50
    alt: Logo
markup:
  goldmark:
    renderer:
      unsafe: true