---
title: Lawless President
author: mtgingrass
date: '2020-08-30'
slug: lawless-president
categories:
  - Reddit
  - Trump
tags:
  - Reddit
  - Trump
---


> Throughout the Republican National Convention, speakers tried to paint President Trump as the "law and order" president. But Trump has routinely shown a disregard for the law, sown chaos across the country, and promoted disorder in our society. Michael Gordon is a longtime Democratic strategist, a former spokesman for the Justice Department, and the principal for the strategic-communications firm Group Gordon. This is an opinion column. The thoughts expressed are those of the author. Visit Business Insider's homepage for more stories.

> Throughout the Republican National Convention, a variety of voices cast the incumbent as the "law and order" president.

> According to President Trump's offspring, the dog whistlers of St. Louis and various elected officials like Kentucky Attorney General Daniel Cameron, Democrats are soft on crime. They even encourage crime and are hell-bent on abolishing the police.

> These speakers have assured people that Trump will keep law-abiding Americans safe, even if it means deploying US troops on our own soil.

<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=qf_sp_asin_til&ad_type=product_link&tracking_id=hatro-20&marketplace=amazon&region=US&placement=B083C5Q8VJ&asins=B083C5Q8VJ&linkId=bbd98b02435524739da4a03f70261dfc&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=qf_sp_asin_til&ad_type=product_link&tracking_id=hatro-20&marketplace=amazon&region=US&placement=B081FV1Y57&asins=B081FV1Y57&linkId=7c28d06cfdeb789e825eb6199b1edaf3&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>

> But this narrative, like many spun by the Trump campaign, is more farce than fact, another attempt to draw focus from Trump's handling of the pandemic, economy, and racial injustice. Make no mistake, Trump is not the law and order President. He is the lawless and disorder President.

> Lawless Our "law and order" president has consistently shown a disregard for the "law" portion of that idea throughout his time in office.

> He has abused the pardon power to shrug his shoulders at corruption - perhaps because it's fundamental to his life's work. He has granted clemency to Jared Kushner pal Patrick Nolan, who pled guilty to racketeering; Conrad M. Black, a friend convicted of fraud; and former governor. and Celebrity Apprentice contestant Rod. Blagojevich, who infamously tried to sell a US Senate seat.

> Like the member of a good crime syndicate, Trump protects his buddies who protect him. He rewarded Roger Stone's silent loyalty with commutation. His Justice Department dropped charges against Michael Flynn after Flynn pleaded guilty to the charges. And with Steve Bannon's days of freedom in peril, it feels as if the question isn't if Trump will pardon him but when.

> Instead of standing up for truth in justice, Trump bristles at perjury charges - such as when Rudy Giuliani cried "perjury trap" to explain why the president would not be interviewed by Robert Mueller. Truth is truth, despite Giuliani's claim to the contrary, and there's no need to claim "perjury trap" when the facts are on your side.

> Trump has even built lawlessness into his public policy. Dozens of officials from other countries have spent money at his properties, likely in violation of the Emoluments Clause of the Constitution. His foreign policy decisions reek of corruption and conflicts of interest, and his immigration policies have likely violated domestic and international law.

> Crooked Even before his presidency, Trump was involved in more than 3,500 lawsuits, including for his "sham university" that defrauded students and for underpaying his undocumented employees.

<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=qf_sp_asin_til&ad_type=product_link&tracking_id=hatro-20&marketplace=amazon&region=US&placement=B07MCYCL4T&asins=B07MCYCL4T&linkId=e5e5f6d2690d4e4f2f0484fe8986f879&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=qf_sp_asin_til&ad_type=product_link&tracking_id=hatro-20&marketplace=amazon&region=US&placement=B07HDV7SK3&asins=B07HDV7SK3&linkId=7e822a29957385c35f95bb2a4a31849a&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>
> Then, there were his 2016 election crimes. The Republican-led US Senate Intelligence Committee did what Special Counsel Robert Mueller failed to do: prove decisively that Trump's campaign colluded with Russia. Meanwhile, there is strong evidence that Trump also broke campaign finance laws that same year by participating in hush-money payments to women.

> Ultimately, some of his crimes in office would be too clear and obvious for Trump to slink away from entirely. He was of course impeached -- but not convicted -- of crimes that can be punishable by several years in prison.

> Despite his stain on history, Trump seems ever more emboldened to cross legal and ethical lines.

> Disordered President Trump also fails on the second half of his "law and order" claim.,

> His words and actions don't help maintain order but rather sow division, unrest, and chaos.

> He speaks out against an "angry mob" of peaceful protesters but encourages mob violence at his rallies. He calls himself an ally to peaceful protesters but sends federal troops to tear gas them so he can have a photo op. He calls on foreign leaders not to kill their protesters but warns Americans that "when the looting starts, the shooting starts."

> It's never been about order. It's a faux strength masking a President's deep insecurities.

> A president who openly meddles with the Justice Department cannot be a shield for our nation. A president who calls peaceful demonstrators "thugs" but sees "very fine people on both sides" in Charlottesville cannot restore "order" to a nation awakened to racial injustice.

> If Donald Trump were truly a man of order, he would unequivocally condemn this week's murder of protesters allegedly at the hands of a young supporter. He would turn off the heated rhetoric that inspires far-right violence. But by now we know he's not capable.

> Trump claiming the mantle of law and order is like the US claiming victory over COVID-19. It immediately fails the smell test.

> There are many words to describe heads of state who freely bend, flout, and manipulate laws for personal and political ends. Think dictator or strongman, not president.

> Trump's past and present prove that he is the last person capable of hoisting the law and order banner, and the last person we need in the White House for four more years. It's not what it is.